"""Reproduce protocol ID tables from the pinned Python reference; sends no I/O.

Run with the upstream Python dependencies installed. Generated Rust contains
facts and attribution only; protocol behaviour is implemented and tested by hand.
"""
import importlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
import sys
sys.path.insert(0, str(ROOT))
rows = []
def add(provider, vid, pid, name, variant="", param=0):
    rows.append((provider, vid, pid, name, variant, param))
def table(provider, vid, attribute="KNOWN"):
    m = importlib.import_module("providers." + provider)
    for pid, value in getattr(m, attribute).items():
        if isinstance(value, tuple):
            add(provider, vid, pid, value[0], "", int(value[1]))
        else:
            add(provider, vid, pid, value)
for provider, vid, attr in [("razer",0x1532,"KNOWN"),("asus",0x0b05,"KNOWN"),("audeze",0x3329,"KNOWN"),("wlmouse",0x36a7,"KNOWN"),("playstation",0x054c,"KNOWN"),("nintendo",0x057e,"KNOWN"),("eightbitdo",0x2dc8,"KNOWN"),("astro",0x046d,"PIDS"),("hyperx",0x03f0,"PIDS"),("hyperx_cloud3",0x03f0,"PIDS"),("jbl",0x0ecb,"PIDS"),("keychron",0x3434,"PIDS"),("corsair",0x1b1c,"PIDS"),("gwolves",0x33e4,"WIRED")]:
    table(provider,vid,attr)
for pid in importlib.import_module("providers.wlmouse").RECEIVERS:
    if not any(row[0]=="wlmouse" and row[2]==pid for row in rows): add("wlmouse",0x36a7,pid,"WLmouse receiver")
add("gwolves",0x33e4,0x3854,"G-Wolves mouse")
for pid, name in importlib.import_module("providers.corsair").NXP_PIDS.items(): add("corsair",0x1b1c,pid,name,"nxp")
for pid in [0x1e,0x1c]: add("lamzu",0x373e,pid,"LAMZU Maya X")
add("lofree",0x388d,0x25,"Lofree Hyzen")
add("barracuda",0x1532,0x053a,"Razer Barracuda Pro")
add("am_infinity",0x3151,0x5007,"AM Infinity 8K Mouse")
add("hyperx_alpha2",0x03f0,0x08be,"HyperX Cloud Alpha 2")
for vid,pid,name in [(0x5253,0x1020,"MCHOSE M7 Ultra"),(0x3837,0x100b,"MCHOSE A7 V2 Ultra"),(0xa8a5,0x2255,"MCHOSE G7")]: add("mchose",vid,pid,name)
for vid,pids in importlib.import_module("providers.pulsar").PIDS.items():
    for pid,name in pids.items(): add("pulsar",vid,pid,name)
s=importlib.import_module("providers.steelseries")
for attr in ["MODELS","MOUSE_MODELS","CLASSIC_MODELS"]:
    for pid,value in getattr(s,attr).items(): add("steelseries",0x1038,pid,value[0],value[-1].__name__)
l=importlib.import_module("providers.logitech")
for pid,name in l.HEADSETS.items(): add("logitech",0x046d,pid,name,"headset")
for pid in l.RECEIVERS: add("logitech",0x046d,pid,"Logitech receiver","receiver")
q=lambda s:json.dumps(s,ensure_ascii=False)
text='// Generated by tools/port_catalog.py from upstream 1.13.0; retain protocol credits.\n'
text+='#[derive(Clone, Copy, Debug)]\npub struct Device { pub provider: &\'static str, pub vid: u16, pub pid: u16, pub name: &\'static str, pub variant: &\'static str, pub parameter: u8 }\n'
text+='pub const DEVICES: &[Device] = &[\n'
for p,vid,pid,name,variant,param in sorted(rows): text+=f'    Device {{ provider:{q(p)}, vid:0x{vid:04x}, pid:0x{pid:04x}, name:{q(name)}, variant:{q(variant)}, parameter:{param} }},\n'
text+='];\n'
a=importlib.import_module("providers.audeze")
text+='pub const AUDEZE_REQUESTS: &[&[u8]] = &[\n'+''.join('    &'+repr(packet)+',\n' for packet in a.REQUESTS)+'];\n'
(ROOT/'crates/providers/src/catalog.rs').write_text(text,encoding='utf-8')
(ROOT/'crates/providers/tests/catalog-fixtures.json').write_text(json.dumps(sorted(rows),indent=2)+'\n')
print(f'Generated {len(rows)} device IDs')
